pipeline {
    agent any
    tools {
        nodejs "node"
    }
    parameters {
        string(name:'container_name', defaultValue: 'pagina_web', description: 'Nombre del contenedor de Docker')
        string(name:'image_name', defaultValue: 'pagina_img', description:'Nombre de la imagen en docker')
        string(name:'tag_image', defaultValue:'lts', description: 'Tag de la imagen')
        string(name:'conteiner_por', defaultValue: 80 , description: 'Puerto que usa el contenedor')
    }

    stages{
        stage('install'){
            steps{
                git branch: 'develop', url: 'https://github.com/Gonveliz/jenkins-practice.git'
                dir('frontend'){
                    sh 'npm install'
                }
            }
        }
        stage('test'){
            steps{
                dir('frontend'){
                    sh 'npm run test'
                }
            }
        }
    }
}